"""Score a fleet, rank by risk, write the daily digest."""
from __future__ import annotations

import argparse
from pathlib import Path

from rich.console import Console
from rich.markdown import Markdown

from .data_loader import load_fleet
from .explainer import explain_well, top_drivers
from .features import featurize_fleet
from .model import ESPRiskModel


DEFAULT_MODEL_PATH = "artifacts/esp_risk_model.joblib"
DEFAULT_DATA_DIR = "data/synthetic"


def build_digest(
    fleet_dir: str = DEFAULT_DATA_DIR,
    model_path: str = DEFAULT_MODEL_PATH,
    top_n: int = 10,
    explain: bool = True,
) -> str:
    fleet = load_fleet(fleet_dir)
    if not fleet:
        return f"No wells found in {fleet_dir}."

    features = featurize_fleet(fleet)
    model = ESPRiskModel.load(model_path)
    probs = model.predict_proba(features)
    contribs = model.feature_contributions(features)

    ranking = sorted(zip(features.index, probs), key=lambda x: -x[1])[:top_n]

    lines = [
        f"# ESP Failure Risk — Daily Digest",
        f"\nTop {len(ranking)} wells by 30-day failure probability. Generated by ESP Failure Risk Agent.\n",
        "| Rank | Well | Risk | Rationale |",
        "|---|---|---|---|",
    ]

    for rank, (well_id, prob) in enumerate(ranking, 1):
        if explain and prob > 0.3:
            drivers = top_drivers(contribs.loc[well_id], k=4)
            rationale = explain_well(
                well_id=well_id,
                risk_score=float(prob),
                feature_values=features.loc[well_id].to_dict(),
                top_drivers=drivers,
            ).replace("\n", " ")
        else:
            # Static rationale tier when LLM explanations are skipped.
            if prob >= 0.7:
                rationale = "HIGH risk — investigate immediately. Run with explanations for diagnosis."
            elif prob >= 0.4:
                rationale = "Moderate risk — schedule review within 7 days."
            else:
                rationale = "Low risk — routine monitoring."
        lines.append(f"| {rank} | {well_id} | {prob:.0%} | {rationale} |")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Rank ESP wells by 30-day failure risk.")
    parser.add_argument("--data-dir", default=DEFAULT_DATA_DIR)
    parser.add_argument("--model", default=DEFAULT_MODEL_PATH)
    parser.add_argument("--top", type=int, default=10)
    parser.add_argument("--no-explain", action="store_true")
    args = parser.parse_args()

    digest = build_digest(
        fleet_dir=args.data_dir,
        model_path=args.model,
        top_n=args.top,
        explain=not args.no_explain,
    )
    Console().print(Markdown(digest))


if __name__ == "__main__":
    main()
